### ISSUE TITLE
'cat' on stdin produces "Input/output error"

### ISSUE THREAD

**Issue by Droggelbecher** [xonsh/xonsh#1462]
On 0.3.4:

> $ cat
> /bin/cat: -: Input/output error

**Comment by gforsyth** [comment]
Hi @Droggelbecher, thanks for reporting.  Could you try updating and see if your issue has already been fixed?  We just released version 0.4.4 last night.

**Comment by scopatz** [comment]
@Droggelbecher - yeah, this seems to work for me on v0.4.4

**Comment by Droggelbecher** [comment]
After updating to latest archlinux package (https://aur.archlinux.org/packages/xonsh):
```
~master $ /usr/bin/xonsh --no-rc --version
('xonsh/0.4.4',)
~master $ /usr/bin/xonsh --no-rc 
... $ $XONSH_VERSION
'0.4.3'
... $ cat
/usr/bin/cat: -: Input/output error
... $ 
```
(prompt string substituted with '... $' in quote)

Due to the apparent version number pecularity I'm not a 100% sure I am at 0.4.4 yet though...

**Comment by Droggelbecher** [comment]
Don't know what was wrong with my installation, reinstalled from latest git, now it works, thanks & sorry for the false bug!

**Comment by Droggelbecher** [comment]
This is getting weirder by the minute.
The same installation as above (didn't even reboot the machine).
It seems that the problem still persists, but *only* if cat is the first command being run in a new xonsh instance:

```
~ master $ cat
/bin/cat: -: Input/output error
~ master $ cat
test
test
~ master $ which xonsh
/usr/local/bin/xonsh
~ master $ /usr/local/bin/xonsh --version
xonsh/0.4.4.dev217.dev217
~ master $ $XONSH_VERSION
'0.4.4.dev217.dev217'
~ master $ cd repos/git/xonsh/
~/repos/git/xonsh master $ git log -n 1
commit 81558020e49c3686f47c1346646f397e04400bb4
Merge: df00f02 f1ac29a
Author: Anthony Scopatz <scopatz@gmail.com>
Date:   Tue Aug 2 13:19:50 2016 -0700

    Merge pull request #1523 from xonsh/remove_anaconda_build
    
    Remove anaconda build
~/repos/git/xonsh master $ 
```

```
~/repos/git/xonsh master $ cat
/bin/cat: -: Input/output error
~/repos/git/xonsh master $ cat
test
test
~/repos/git/xonsh master $ 
```

```
~ master $ echo 'test'
test
~ master $ cat
test
test
```

**Comment by laerus** [comment]
This seems solved on current master, feel free to reopen!

**Comment by Droggelbecher** [comment]
Seems to still be there (recent master from today), don't know yet what causes this, but might seem to happen more often under high load

**Comment by gforsyth** [comment]
Hey @Droggelbecher -- could you try out the latest master?  I believe this issue has been resolved by #1758

**Comment by scopatz** [comment]
Any word on this @Droggelbecher?

**Comment by Droggelbecher** [comment]
sorry, got over this it seems.
Can not reproduce anymore w/ recent xonsh, so seems fixed, thanks!

**Comment by scopatz** [comment]
Woohoo!
